In [16]:
import pandas as pd

In [17]:
df_housing=pd.read_csv("housing.csv")

In [18]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [19]:
df_housing.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [20]:
df_housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [21]:
median=df_housing['total_bedrooms'].median()

In [22]:
df_housing['total_bedrooms']=df_housing['total_bedrooms'].fillna(median)

In [23]:
df_housing['total_bedrooms'].isnull().sum()

np.int64(0)

In [24]:
df_housing=pd.get_dummies(df_housing,columns=['ocean_proximity'])

In [25]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,False,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,False,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,False,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,False,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,False,True,False,False,False
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,False,True,False,False,False
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,False,True,False,False,False
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,False,True,False,False,False
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,False,True,False,False,False

In [27]:
ocean_cols = [
    'ocean_proximity_<1H OCEAN',
    'ocean_proximity_INLAND',
    'ocean_proximity_ISLAND',
    'ocean_proximity_NEAR BAY',
    'ocean_proximity_NEAR OCEAN'
]

df_housing[ocean_cols]=df_housing[ocean_cols].astype(int)

In [28]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0,0,0,1,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0,0,0,1,0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0,0,0,1,0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0,0,0,1,0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,0,1,0,0,0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,0,1,0,0,0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,0,1,0,0,0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,0,1,0,0,0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,0,1,0,0,0

In [32]:
from sklearn.model_selection import train_test_split

features=['longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income']+ocean_cols

X=df_housing[features]
y=df_housing['median_house_value']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)

(16512, 13)
(4128, 13)

In [33]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)    
X_test = scaler.transform(X_test)

In [36]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
model_baseline = Sequential([
    Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)  # Regression ke liye 1 output
])

model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=30, batch_size=32, verbose=0)

In [37]:
history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=30, batch_size=32, verbose=1)

Epoch 1/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4789719552.0000 - mae: 49525.3242 - val_loss: 4986316800.0000 - val_mae: 50048.0820
Epoch 2/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4751852544.0000 - mae: 49336.4062 - val_loss: 4954898944.0000 - val_mae: 49893.9375
Epoch 3/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4718203392.0000 - mae: 49164.9062 - val_loss: 4927282688.0000 - val_mae: 49756.9492
Epoch 4/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4688085504.0000 - mae: 49010.2461 - val_loss: 4902321152.0000 - val_mae: 49629.3125
Epoch 5/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4660817920.0000 - mae: 48867.1367 - val_loss: 4879812096.0000 - val_mae: 49517.0547
Epoch 6/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4636099072.0000 - mae: 48736.1719 - val_loss: 4859390464.0000 - val_mae: 49417.5000
Epoch 7/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4613530624.0000 - mae: 48613.1250 - val_loss: 4840711680.0000 - val_mae: 49327.0273
Epoch 8/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4592806912.0000 - mae: 48497.6133 - val_loss: 4823471104.0000 - val_mae: 49240.6094
Epoch 9/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4573708288.0000 - mae: 48389.6172 - val_loss: 4807584768.0000 - val_mae: 49163.0352
Epoch 10/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4555972608.0000 - mae: 48287.8281 - val_loss: 4792898560.0000 - val_mae: 49093.7773
Epoch 11/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4539497984.0000 - mae: 48192.5469 - val_loss: 4779445760.0000 - val_mae: 49030.4531
Epoch 12/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4524213248.0000 - mae: 48103.5273 - val_loss: 4766916096.0000 - val_mae: 48972.1719
Epoch 13/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4509925376.0000 - mae: 48020.1133 - val_loss: 4755294208.0000 - val_mae: 48916.5352
Epoch 14/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 4496503808.0000 - mae: 47940.5898 - val_loss: 4744355328.0000 - val_mae: 48862.9844
Epoch 15/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4483849728.0000 - mae: 47864.2461 - val_loss: 4734079488.0000 - val_mae: 48811.9648
Epoch 16/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4471860736.0000 - mae: 47790.7891 - val_loss: 4724386816.0000 - val_mae: 48763.7852
Epoch 17/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4460554752.0000 - mae: 47720.6133 - val_loss: 4715225600.0000 - val_mae: 48717.8203
Epoch 18/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4449891840.0000 - mae: 47654.6484 - val_loss: 4706525696.0000 - val_mae: 48672.9766
Epoch 19/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4439756800.0000 - mae: 47591.2617 - val_loss: 4698235904.0000 - val_mae: 48627.5508
Epoch 20/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4430149632.0000 - mae: 47530.7383 - val_loss: 4690313728.0000 - val_mae: 48586.3047
Epoch 21/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4420924416.0000 - mae: 47472.2617 - val_loss: 4682690560.0000 - val_mae: 48544.6484
Epoch 22/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4412061184.0000 - mae: 47415.1680 - val_loss: 4675380224.0000 - val_mae: 48504.0859
Epoch 23/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4403598848.0000 - mae: 47360.3633 - val_loss: 4668291072.0000 - val_mae: 48463.2188
Epoch 24/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4395461120.0000 - mae: 47307.0586 - val_loss: 4661447680.0000 - val_mae: 48422.1211
Epoch 25/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4387648512.0000 - mae: 47255.0430 - val_loss: 4654903808.0000 - val_mae: 48382.7695
Epoch 26/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4380077056.0000 - mae: 47204.4180 - val_loss: 4648537600.0000 - val_mae: 48343.9023
Epoch 27/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4372824064.0000 - mae: 47155.4258 - val_loss: 4642425856.0000 - val_mae: 48306.2539
Epoch 28/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4365805056.0000 - mae: 47107.7852 - val_loss: 4636530176.0000 - val_mae: 48270.0469
Epoch 29/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4359000576.0000 - mae: 47062.1250 - val_loss: 4630861312.0000 - val_mae: 48236.0273
Epoch 30/30
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4352337920.0000 - mae: 47017.4219 - val_loss: 4625257472.0000 - val_mae: 48201.8711

In [42]:
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

# 1. Training data par predictions nikalein
train_pred = model_baseline.predict(X_train)

# Training RMSE aur R2 calculate karein

print("RMSE and R2 FOR TRAING DATA")
print( np.sqrt(mean_squared_error(y_train, train_pred)))
print(r2_score(y_train, train_pred))



# 2. Test/Validation data par predictions nikalein (Agar aapke paas X_test aur y_test hain)
print("RMSE AND R2 FOR TESTING DATA")
test_pred = model_baseline.predict(X_test)

print( np.sqrt(mean_squared_error(y_test, test_pred)))
print(r2_score(y_test, test_pred))

516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step
RMSE and R2 FOR TRAING DATA
66350.97908097185
0.6706669523652402
RMSE AND R2 FOR TESTING DATA
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 747us/step
67920.35974432112
0.6479591223504322